apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 31001
      nodePort: 31001
      targetPort: http-port
      protocol: TCP
